apiVersion: v1
kind: Pod
metadata:
  name: kata-pod
  namespace: default
spec:
  runtimeClassName: kata
  containers:
    - name: sleep
      image: alpine
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: loopmount
          mountPath: /dev/xda
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
  volumes:
  - name: loopmount
    hostPath: 
      path: /dev/loop1
