---
kind: RuntimeClass
apiVersion: node.k8s.io/v1beta1
metadata:
    name: kata
handler: kata
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1beta1
metadata:
    name: kata-qemu
handler: kata-qemu
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1beta1
metadata:
    name: kata-nemu
handler: kata-nemu
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1beta1
metadata:
    name: kata2
handler: kata2
